server:
  port: 8080

spring:
  application:
    name: "products"
    version: 1.0
  config:
    import: "configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"