spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleshop_product
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    enabled: true
