spring:

  application:
    name: "configserver"

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/m4rcingsxr/simpleshop-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate: # The readiness probe determines if the application is ready to handle requests
      enabled: true
    livenessstate: # The liveness probe determines if the application is alive
      enabled: true
  endpoint:
    health:
      probes: # enabling probes for health checks in the application
        enabled: true


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
